apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: flask-app   # Namespace reference
spec:
  type: ClusterIP  # Use NodePort or LoadBalancer if you need external access
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis

