apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.common.resourceName.db }}-pvc
  namespace: {{ .Values.common.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
