apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-app-test
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30021
  type: NodePort

