apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config.json: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerHub.registry .Values.dockerHub.username .Values.dockerHub.password (printf "%s:%s" .Values.dockerHub.username .Values.dockerHub.password | b64enc) | b64enc }}
