name: Continous Deployment Pipeline
on:
  push:
    tags: 
      - "v*"
  workflow_dispatch:


env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/flask-app


jobs:
  tag-and-push:
    runs-on: self-hosted
    steps:
      - name: Login to Docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: tag docker image
        run: |
          sudo docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
      - name: Push to Dockerhub
        run: |
          sudo docker push ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}

  deploy:
    runs-on: self-hosted
    steps:
      - name: Change version
        run: |
          sed -i "s/<VERSION>/${{ github.ref_name }}/g" tf-k8s/k8s-manifests/flask-app-deployment.yaml
      
      - name: Copy TF file to run folder
        run: |
          cp -rfp tf-k8s/k8s-manifests ~/.git-tf-ops/k8s-manifests
          cp tf-k8s/main.tf ~/.git-tf-ops/
          cp tf-k8s/variables.tf ~/.git-tf-ops/
  
  clean:
    runs-on: self-hosted
    needs: tag-and-push
    steps:
      - name: remove all images
        run: |
          sudo docker image rm ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          sudo docker image rm ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
      # - name: Remove TF directory
      #   run: |
      #     rm -rf ~/.git-tf-ops/k8s-manifests
      #     rm ~/.git-tf-ops/main.tf
      #     rm ~/.git-tf-ops/variables.tf
  


  # deploy-to-production:
  #   runs-on: self-hosted
  #   environment:
  #       name: staging
  #       url: http://ec2-54-254-129-220.ap-southeast-1.compute.amazonaws.com:9090
  #   steps:
  #     - name: Login to Docker hub
  #       run: |
  #         ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP_ADDR }} 'echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin'
      
  #     - name: Remove old version
  #       run: |
  #         ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP_ADDR }} 'sudo docker rm -vf ${{ env.DOCKER_CONTAINER_NAME }}'

  #     - name: Pull images
  #       run: |
  #         ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP_ADDR }} 'sudo docker pull ${{ env.DOCKER_IMAGE }}'
      
  #     - name: Setup new version
  #       run: |
  #         ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP_ADDR }} 'sudo docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 8080:8080 -e FLASK_APP=${{ secrets.FLASK_APP }} -e FLASK_DEBUG=${{ secrets.FLASK_DEBUG }} -e GUNICORN_BIND=${{ secrets.GUNICORN_BIND }} -e PORT=${{ secrets.PORT }} -e DATABASE_URI=${{ secrets.DATABASE_URI }} --network ${{ env.DOCKER_NETWORK }} ${{ env.DOCKER_IMAGE }}'
      
      


