# name: Continous Integration

# on:
#   push:
#     branches:
#       - '**'
# jobs:
#   build:
#     name: Build
#     runs-on:
#       - self-hosted
#       - k8s-runner
#     steps:
#       - name: Get Pods
#         run: |
#           set -ex
#           cd $HOME
#           wget https://dl.k8s.io/release/v1.26.0/bin/linux/arm64/kubectl
#           chmod +x ./kubectl
#           ./kubectl auth can-i get pods
#           ./kubectl get pods -A

name: Actions Runner Controller Demo
on:
#  workflow_dispatch:
  push:
     branches:
      - '**'

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
      - name: say-hello
        run: |
          whoami
          echo "hello"
          sudo apt-get update
          sudo apt-get install curl libcurl4 -y
          cd $HOME
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl

          kubectl get pods -A

      