# name: Continous Integration

# on:
#   push:
#     branches:
#       - '**'
# jobs:
#   build:
#     name: Build
#     runs-on:
#       - self-hosted
#       - k8s-runner
#     steps:
#       - name: Get Pods
#         run: |
#           set -ex
#           cd $HOME
#           wget https://dl.k8s.io/release/v1.26.0/bin/linux/arm64/kubectl
#           chmod +x ./kubectl
#           ./kubectl auth can-i get pods
#           ./kubectl get pods -A

name: Actions Runner Controller Demo
on:
#  workflow_dispatch:
  push:
     branches:
      - '**'

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
      - name: Test runner in k8s
        run: |
          cd $HOME
          sudo apt-get update
          sudo apt-get install -y curl libcurl4
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
          kubectl version --client

